config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'home#login'
  post '/login' => 'home#process_login', as: 'process_login'

  resources :call_requests do
    member do
      get 'respond'
      get 'check_response'
      
      post 'process_response'
    end
  end

  root 'home#index'
end

app/models/call_request.rb
class CallRequest < ActiveRecord::Base
  belongs_to :user

  RESPONSES = {
    not_found: 'No estoy en la oficina',
    not_appointment: 'No tiene cita'
  }

  def to
    user
  end

  def has_response?
    self.response.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :call_requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  before_filter :set_headers

  private

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Expose-Headers'] = 'ETag'
    headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
    headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match'
    headers['Access-Control-Max-Age'] = '86400'
  end
end

app/controllers/call_requests_controller.rb
class CallRequestsController < ApplicationController
  def create
    from = params[:from]
    to = params[:to]

    user = User.where('name LIKE ?', "%#{to}%").first

    if user
      @call_request = CallRequest.create(user_id: user.id, from: from)

      Pusher["assistant_for_#{user.id}"].trigger('call', {
        message: from,
        id: @call_request.id
      })

      render json: @call_request.id
    else
      render json: { error: "Usuario no encontrado" }
    end
  end

  def respond
    @call_request = CallRequest.find(params[:id])
  end

  def process_response
    @call_request = CallRequest.find(params[:id])

    if params[:response] == 'wait'
      response = "Espere #{params[:minutes]} minutos"
    else
      response = CallRequest::RESPONSES[params[:response].to_sym]
    end

    @call_request.response = response
    @call_request.save

    redirect_to root_path
  end

  def check_response
    @call_request = CallRequest.find(params[:id])

    render json: { status: @call_request.has_response?, response: @call_request.response }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if cookies.signed[:current_user_id].blank?
      redirect_to login_path
    else
      @user = User.find(cookies.signed[:current_user_id])
    end
  end

  def login
  end

  def process_login
    name = params[:name]

    if user = User.where('name LIKE ?', "%#{name}%").first
      cookies.signed[:current_user_id] = user.id

      redirect_to root_path
    else
      redirect_to login_path, flash: 'Usuario no encontrado'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/call_requests_helper.rb
module CallRequestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/call_requests/respond.html.erb
<h2>Responder mensaje de <%= @call_request.from %></h2>
<%= form_tag(process_response_call_request_path(@call_request), method: 'post') do |f| %>
  <div>
    <%= radio_button_tag(:response, 'wait') %>
    <%= label_tag(:response_wait, 'Esperar <input id="minutes" type="number" name="minutes" value="5" min="5"> minutos'.html_safe) %>
  </div>
  <div>
    <%= radio_button_tag(:response, "not_found") %>
    <%= label_tag(:response_not_found, 'No estoy en la oficina') %>
  </div>
  <div>
    <%= radio_button_tag(:response, "not_appointment") %>
    <%= label_tag(:response_not_appointment, 'No tiene cita') %>
  </div>
  <%= submit_tag('Responder') %>
<% end %>

app/views/home/index.html.erb
<h2>Mensajes entrantes</h2>
<% @user.call_requests.each do |call_request| %>
  <div class="call_request" id="call_request_<%= call_request.id %>">
    <span>
      <strong>De:</strong>
      <%= call_request.from %>
    </span>
    <span>
      <strong>Fecha:</strong>
      <%= l(call_request.created_at.to_date, format: :default) %> (<%= time_ago_in_words(call_request.created_at, include_seconds: true) %>)
    </span>
    <% if call_request.has_response? %>
      <span>
        <strong>Respuesta:</strong>
        <%= call_request.response %>
      </span>
    <% else %>
      <a href="<%= respond_call_request_path(call_request) %>">Responder</a>
    <% end %>
  </div>
<% end %>

app/views/home/login.html.erb
<h2>Ingresar</h2>
<%= form_tag(process_login_path, method: 'post') do |f| %>
  <%= label_tag(:name, 'Ingrese su nombre:') %>
  <%= text_field_tag(:name) %>
  <%= submit_tag('Entrar') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NaoAssistant</title>
  <script src="//js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <% if @user %>
  <script type="text/javascript">
    Pusher.log = function(message) {
      if (window.console && window.console.log) {
        window.console.log(message);
      }
    };

    var pusher = new Pusher('729bec284ffe13018c08'),
        channel = pusher.subscribe('assistant_for_<%= @user.id %>');

    channel.bind('call', function(data) {
      if (data.message) {
        showNotification('Tiene un nuevo mensaje de ' + data.message, data.id);
      }
    });
  </script>
  <% end %>
</head>
<body>
  <div id="new_call_request"><p>Tiene un nuevo mensaje de {{data}}.</p><a href="#">Responder</a></div>
  <header id="app_header">
    <h1>NAO Assistant</h1>
  </header>

  <section id="app_main">
    <%= yield %>
  </section>
</body>
</html>